Feature/group1/tarea1
Ditmar/tupiza-material pull request #6
Opened 2023-08-17 14:37 UTC by Cancerius

capture of my task api

2023-08-29 20:49 UTC, Ditmar requested changes
No esta dentro del scope de lo que se pidio por lo tanto esta pr esta declinada

2023-08-29 20:49 UTC, Ditmar commented on src/context/about/index.jsx
> +            <h1>Holas</h1>
cambia esta parte del codigo no tenemos un Holas en el figma

2023-08-29 20:49 UTC, Ditmar commented on src/context/characters/index.jsx
> +            <h1>Hola</h1>
lo mismo aqui presumo que la implementaicon no hace lo que tienen que hacer

2023-08-29 20:49 UTC, Ditmar commented on src/context/home/index.jsx
> +            {isLoading? <h1>Cargando...</h1> : data?.results?.map((item, index) => (
estos cambios estan fuera del scope del ticket

2023-08-29 21:16 UTC, Cancerius commented
Inge buenas tarde una consulta a que se refiere con scope.?

2023-08-31 20:03 UTC, Cancerius commented
![image](https://github.com/Ditmar/tupiza-material/assets/105614687/374b56a6-29e6-4e31-91e4-d5e78afcd06d)

2023-09-09 02:42 UTC, Ditmar approved these changes
buena pr

2023-09-09 02:43 UTC, closed without merging